# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trunk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F5arp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arp_ip', models.GenericIPAddressField()),
                ('arp_mac', models.CharField(max_length=10)),
                ('arp_vlan', models.CharField(max_length=100, null=True)),
                ('arp_status', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.Site')),
            ],
        ),
        migrations.CreateModel(
            name='F5vcmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcmp_name', models.CharField(max_length=100)),
                ('vcmp_ip', models.GenericIPAddressField()),
                ('env_type', models.CharField(max_length=10)),
                ('tm_type', models.CharField(max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.Site')),
            ],
        ),
        migrations.AddField(
            model_name='f5arp',
            name='vcmp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f5app.F5vcmp'),
        ),
    ]
